"""empty message

Revision ID: 378f199289d0
Revises: f6b8bcffc58c
Create Date: 2025-01-11 02:24:23.981827

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '378f199289d0'
down_revision: Union[str, None] = 'f6b8bcffc58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('false_state_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('played_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('won', sa.BOOLEAN(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__false_state_stats__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__false_state_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('false_state_stats')
    # ### end Alembic commands ###
