"""empty message

Revision ID: 43f9499efd93
Revises: d599d0020ffc
Create Date: 2025-01-19 19:42:26.623058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f9499efd93'
down_revision: Union[str, None] = 'd599d0020ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simon_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('played_at', sa.DATE(), nullable=False),
    sa.Column('all_length', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__simon_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simon_stats')
    # ### end Alembic commands ###
