"""empty message

Revision ID: 9755a19c4228
Revises: f6b8bcffc58c
Create Date: 2025-01-11 16:38:48.521833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9755a19c4228'
down_revision: Union[str, None] = 'f6b8bcffc58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('name_image', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__images'))
    )
    op.create_table('names_memory_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('played_at', sa.DATE(), nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), nullable=False),
    sa.Column('wrong_answers', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__names_memory_stats'))
    )
    op.create_table('viewed_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), nullable=False),
    sa.Column('used_in_game', sa.INTEGER(), nullable=False),
    sa.Column('correct', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__viewed_images'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed_images')
    op.drop_table('names_memory_stats')
    op.drop_table('images')
    # ### end Alembic commands ###
