"""empty message

Revision ID: d599d0020ffc
Revises: e8dbec3ba607
Create Date: 2025-01-19 18:10:57.028098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd599d0020ffc'
down_revision: Union[str, None] = 'e8dbec3ba607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('played_at', sa.DATE(), nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), nullable=False),
    sa.Column('all_answers', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__words_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words_stats')
    # ### end Alembic commands ###
