ENV = "development"
PATH_PREFIX = "/api/v1"
APP_HOST = "127.0.0.1"
APP_PORT = 8080

DATABASE_NAME = "memory_minder"
DATABASE_HOST = "localhost"
DATABASE_USER = "staff"
DATABASE_PORT = 5431
DATABASE_PASSWORD = "super_secret"

DB_CONNECT_RETRY = 20
DB_POOL_SIZE = 15

ECHO_ENABLED = True

BOT_API_TOKEN = ""
